name = "wallet-monitoring-worker"
main = "src/index.js"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "production"
SERVICE_NAME = "Wallet Monitoring Worker"
MAIN_API_URL = "https://logic-digital-wallet-api.jameharu-no1.workers.dev"
BANKING_API_URL = "https://banking-worker.jameharu-no1.workers.dev"
SECURITY_API_URL = "https://security-worker.jameharu-no1.workers.dev"
INTERNAL_API_KEY = "internal-api-secure-2025-wallet"
AUDIT_SHARED_KEY = "secure-audit-key-2025"
ALERT_THRESHOLD_RESPONSE_TIME = "2000"
ALERT_THRESHOLD_ERROR_RATE = "5"

[[d1_databases]]
binding = "DATABASE"
database_name = "wallet-production-db"
database_id = "534c2f1f-a529-46a5-8ede-e294d3df9d31"

[[kv_namespaces]]
binding = "MONITORING_DATA"
id = "monitoring_data_kv"
