# Root Orchestrator Configuration
# This is a simple orchestrator/router for the multi-worker platform
name = "digital-wallet-orchestrator"
main = "orchestrator.js"
compatibility_date = "2024-08-25"
compatibility_flags = ["nodejs_compat"]

# Service Bindings to individual workers
[[services]]
binding = "MAIN_BOT"
service = "main-bot-worker"

[[services]]
binding = "API_WORKER"
service = "api-worker"

[[services]]
binding = "FRONTEND"
service = "frontend-worker"

[[services]]
binding = "BANKING"
service = "banking-worker"

[[services]]
binding = "SECURITY"
service = "security-worker"

# Environment Variables
[vars]
ACCOUNT_ID = "85bcd386f06541844632ecb984afa9fb"
PROJECT_NAME = "digital-wallet-platform"
ENVIRONMENT = "production"
DOMAIN = "teenoi96.org"
