name: Database Migration

on:
  workflow_dispatch:
    inputs:
      migration_type:
        description: 'Migration operation'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - status
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Database Migration
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Run migrations
        working-directory: ./api
        run: npx wrangler d1 migrations apply ${{ github.event.inputs.environment }}-database
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_D1_MIGRATE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}